name: "Bump Version"

on:
  push:
    branches:
      - "master"

jobs:
  bump-version:
    name: "Bump Version on master"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v1"
      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: "12"
      - name: "Automated Version Bump"
        uses: "tmayr/npm-version-action@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
